### ISSUE TITLE
finish() method results in NameError: name 'unicode' is not defined - python 3.4

### ISSUE THREAD

**Issue by simminni** [verigak/progress#13]
In python 3.4, when I call finish() method on a progress bar object it results in NameError: name 'unicode' is not defined. However this is fine when used in python verison 2.x

Please fix the issue or suggest an alternative approach to avoid running into this issue.

**Comment by verigak** [comment]
I think you are using a different library. There is no `progressbar.py` file or `_format_widgets` function here.
