### ISSUE TITLE
Exception in a loop over a Bar().iter() looses cursor from terminal

### ISSUE THREAD

**Issue by sindreij** [verigak/progress#14]
When a KeyboardInterrupt (or any other exception) is raised inside a loop over a iteratoor gotten from Bar().iter() the terminal is not reset. This means that the cursor is gone. A reset in the terminal fixes it.

    $ python2 test_bar.py 
    Processing |######                          | 19/99Traceback (most recent call last):
      File "test_bar.py", line 8, in <module>
        raise KeyboardInterrupt
    KeyboardInterrupt
    $   # No cursor in the terminal any more

test_bar.py:

    import time

    from progress.bar import Bar

    for i in Bar('Processing').iter(range(1, 100)):
        time.sleep(0.01)
        if i == 20:
            raise KeyboardInterrupt

**Comment by verigak** [comment]
Thanks for fixing this.
