### ISSUE TITLE
Colorizing and stylizing the progress bars \ spinners

### ISSUE THREAD

**Issue by farchy** [verigak/progress#27]
Also started implementing this (using ANSI escape codes), is it something you are open for PR on?
Example:
![screenshot from 2016-04-21 15-28-03](https://cloud.githubusercontent.com/assets/3086947/14708792/c6982e58-07d5-11e6-95b4-ff39f05a5661.png)

**Comment by praiskup** [comment]
I would be interested in https://github.com/python-progress/python-progress.  Though
I would like to see some standard python library for ANSI colors used.

**Comment by farchy** [comment]
Something like [colorama](https://github.com/tartley/colorama) ?

**Comment by verigak** [comment]
I wouldn't like the existing ones to change. However if you want to submit some new ones I would be open to it.

**Comment by praiskup** [comment]
@farchy I was thinking about something like blessings, termcolor, or so.  The reason is
some nontrivial bureaucracy around terminal colors (detection that terminal supports
colors e.g. and fallback to non-colorized version).

**Comment by farchy** [comment]
OK, I'll try moving to one of these libs (currently my own implementation as a `MixIn`)

**Comment by verigak** [comment]
Maybe submit a first PR now to see what you have before going too deep into integrating stuff.

**Comment by BarryThrill** [comment]
Did anyone had any solution for this? :D
