### ISSUE TITLE
iPython console - no progress bar appears

### ISSUE THREAD

**Issue by mat2py** [verigak/progress#33]
This module doesn't seem to work using an iPython console.
- ObsPy version: 1.0.2
- Python 2.7.12
- Anaconda 4.1.1 (64-bit)
- Ubuntu 15.10

Even simply running the example:

```
from progress.bar import Bar
bar = Bar('Processing', max=20)
for i in range(20):
    # Do some work
    bar.next()
bar.finish()
```

results in successful completion but with no progress bar.

Output:

```
In [1]: from progress.bar import Bar
   ...: 
   ...: bar = Bar('Processing', max=20)
   ...: for i in range(20):
   ...:     # Do some work
   ...:     bar.next()
   ...: 
   ...: bar.finish()

In [1]: 

In [1]: 

In [2]: 
```

**Comment by praiskup** [comment]
Not reproducible:
```
$ cd /tmp/
$ git clone https://github.com/python-progress/python-progress.git
Cloning into 'python-progress'...
warning: templates not found /home/praiskup/.git_templates
remote: Counting objects: 135, done.
remote: Total 135 (delta 0), reused 0 (delta 0), pack-reused 135
Receiving objects: 100% (135/135), 623.79 KiB | 189.00 KiB/s, done.
Resolving deltas: 100% (82/82), done.
Checking connectivity... done.
$ export PYTHONPATH=`pwd`/python-progress
$ ipython
Python 2.7.12 (default, Sep  2 2016, 14:46:00) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
[TerminalIPythonApp] WARNING | File not found: '/home/praiskup/.pythonrc'

In [1]: from progress.bar import Bar

In [2]: bar = Bar('Processing', max=20)

In [3]: for i in range(20):    # Do some work
   ...:         bar.next()
   ...:     
Processing |################################| 20/20
In [4]: bar.finish()


In [5]: 


```

**Comment by verigak** [comment]
This seems to be an artifact of iPython. Try this instead:

```python
from progress.bar import Bar
import time

bar = Bar('Processing', max=20)
for i in range(20):
    time.sleep(0.1)
    bar.next()
bar.finish()
`

**Comment by mat2py** [comment]
Still nothing with the `time.sleep(0.1)` code:

```
In [9]: from progress.bar import Bar
   ...: 
   ...: bar = Bar('Processing', max=20)
   ...: for i in range(20):
   ...:     # Do some work
   ...:     time.sleep(0.1)
   ...:     bar.next()
   ...: 
   ...: bar.finish()

In [10]: 
```

Install done with:
```
cd progress/
git clone https://github.com/python-progress/python-progress.git
cd python-progress/
pip install -v -e .
```

It imports fine and runs fine but still no progress bar appears


cd python-progress/

**Comment by verigak** [comment]
Please use the right URL. @praiskup please stop confusing people

**Comment by praiskup** [comment]
URL doesn't matter here.  Or am I wrong?

**Comment by praiskup** [comment]
I.e. I've tested both forks, and I haven't been able to reproduce this.

**Comment by verigak** [comment]
@praiskup That's irrelevant. This is not a platform to advertise your fork.

**Comment by praiskup** [comment]
@mat2py it is much likely you have problems with terminal.  What is the default linux terminal?

**Comment by praiskup** [comment]
`xterm`, `konsole` and `gnome-terminal` works for me.  @mat2py can you please describe better your environment?

**Comment by praiskup** [comment]
Drats!  I misread your comment @mat2py sorry ... you wrote: `iPython console of Spyder`.  I'm not sure how to test there, but it is possible that there is limited terminal feature set.

**Comment by praiskup** [comment]
Of course that means that progress bar should be able to detect this fact, somehow.

**Comment by mat2py** [comment]
Hey praiskup, the Spyder iPython console is a massive GUI distribution (part of Anaconda) and so I would assume it wouldn't have limited functionality.

The version of spyder is 3.0.0.dev0

**Comment by mat2py** [comment]
But it does work in a iPython session in the normal terminal window and so, you're right, it must be some interaction with the Spyder iPython window.

It works with the following things which (I guess) are the iPython controllers?:

Runtime dependencies
- PyQt5 5.2+ or PyQt4 4.6+: PyQt5 is recommended.
- qtconsole 4.2.0+: Enhanced Python interpreter.

**Comment by praiskup** [comment]
`spyder` is actually free software, that allowed me to confirm that it really doesn't work.
I'm unable to tell you whether this is expected, but it definitely could be. I was unable to get
plain terminal (without IPython) and to run some other terminal app to prove that.

It simply looks like they have the terminal in place to allow them to colorize input/output (which is different thing/feature from usual terminal controlling sequences).

**Comment by verigak** [comment]
@mat2py Can you please report what is the result of the following?

```python
import sys
sys.stderr.isatty()
```

**Comment by praiskup** [comment]
That is not a tty, yes python progress could implement alternative non-tty stub (if you are able to ungetc at least).

**Comment by verigak** [comment]
We could do something for non-tty cases, but not much. Keep in mind that this will be the case when someone is redirecting the output to a file too. To be honest, I don't think it is right for spyder to report that it is not a tty.

**Comment by praiskup** [comment]
> I don't think it is right for spyder to report that it is not a tty.

That is not a tty, it is pipe.  Looks like this would require a non-trivial work, should be reported to spyder upstream.

**Comment by mat2py** [comment]
`import sys
sys.stderr.isatty()`

Outputs 'False'

**Comment by Khalilsqu** [comment]
this is not working in jupyter notebook, win64 , python 3.6

**Comment by verigak** [comment]
You should now be able to workaround this the same way as in #50.
