### ISSUE TITLE
self.avg vs. (self.elapsed/self.index)

### ISSUE THREAD

**Issue by clime** [verigak/progress#34]
Shouldn't self.avg be (roughly) equal to self.elapsed/self.index? In my test (file uploading) it comes out differently:

1.578591763973236e-08 (self.avg) vs. 7.149365691934405e-08 (self.elapsed/self.index)

Eta is then not correct (less than actual).

Thanks!

**Comment by praiskup** [comment]
https://bugzilla.redhat.com/1299634

**Comment by praiskup** [comment]
@clime, aka #24.  Have you tried the latest git head of this project?  Last time had a look it did not work.

**Comment by clime** [comment]
Actually, I am sorry, this is not a bug against upstream (i tested with 1.2-7.fc24). With upstream ETA works correctly.

`self.avg` gives very high values (~15728944.785901014) and that's likely because the meaning of it has changed. 

It is no longer: avg 	simple moving average time per item (in seconds) (as stated in docs) but instead it seems to be: items per second.

So probably just README.md update is needed and this can be closed. Thx.

**Comment by praiskup** [comment]
Ouch, you claim semantics of API changed?

**Comment by praiskup** [comment]
FWIW, according to Fedora bug:
http://pkgs.fedoraproject.org/cgit/rpms/python-progress.git/commit/?id=2e851c8ab6e759a75d04d20d763e01e5eb06692f
@clime, can you check the Rawhide is fixed for you?  I could submit updates to stable Fedora too.

**Comment by clime** [comment]
Yes, Fedora-Rawhide version works.

**Comment by verigak** [comment]
So can I merge PR/35 and close this?

**Comment by clime** [comment]
Fine by me but that #35 request is unneeded if you return to the original semantics :). Anyway, this can be closed.

**Comment by verigak** [comment]
This should be fixed now
