### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by lafrenierejm** [verigak/progress#37]
I am interested in packaging this project.  Would it be feasible to have a tagged release?

**Comment by xavfernandez** [comment]
Indeed, a new release would be lovely.
I'd like to vendor it in the next pip version to solve https://github.com/pypa/pip/issues/3015.

**Comment by verigak** [comment]
Any volunteers to test if current master didn't break anything in pip? Otherwise I can release 1.3 with what we have now.

**Comment by xavfernandez** [comment]
@verigak I'm testing it in https://github.com/pypa/pip/pull/4411

**Comment by xavfernandez** [comment]
@verigak Everything seems fine 👍 
(master was 91d9d3cb at the time)

**Comment by xavfernandez** [comment]
ping :)

**Comment by verigak** [comment]
Released 1.3

**Comment by xavfernandez** [comment]
Thanks 👍
