### ISSUE TITLE
After using spinner, cursor is not restored.

### ISSUE THREAD

**Issue by dmitry-mukhin** [verigak/progress#41]
simple

```
    counter = Counter('waiting... ')

    for _ in range(10):
        counter.next()
        time.sleep(1)
```

leaves my console without cursor, so it seems that counter.finish() is not run.

**Comment by abrahamrhoffman** [comment]
In my terminal, I had to run `tput cvvis` afterward to restore the cursor

**Comment by verigak** [comment]
You need to call `finish` explicitly when you are using the counter this way. An alternative pattern is the following:

```python
with Counter('waiting... ') as counter:
    for _ in range(10):
        counter.next()
        time.sleep(1)
```

Both are mentioned on the home page.
