### ISSUE TITLE
Does not print anything with PyCharm IDE

### ISSUE THREAD

**Issue by IbrarYunus** [verigak/progress#50]
I am using PyCharm community Version 2017.3 using a Python 3.6 virtual environment (created with Miniconda) on Windows 10.
When testing the example in the ReadME (to print the bar), nothing prints on the console.

**Comment by verigak** [comment]
This is caused by PyCharm reporting that stdout and stderr are not ttys, i.e. `isatty()` returns `False`.

1f19b5b61c9a8c229d736853fe84ffe088b080ca should allow you to workaround this by setting the `check_tty` flag to `False`. e.g.:

```
bar = Bar('Processing')
bar.check_tty = False
...
```

**Comment by HenrYxZ** [comment]
It's also not working by default with Git Bash, but adding check_tty = false fix it
