### ISSUE TITLE
Spinner.finish() doesn't seem to emit a final newline

### ISSUE THREAD

**Issue by clintolsen** [verigak/progress#51]
The example for the bar shows using finish() when you're done with a progress item. However, I noticed spinner just leaves things hanging. The example doesn't use finish(). I tried it but it seems to be a no-op?

Thanks,

-Clint

**Comment by verigak** [comment]
Thanks, this was an oversight. The clean up done in d9d40736d608a9dcf5476c5e4c4f7eb2de15fc4b should fix this.

**Comment by clintolsen** [comment]
Thanks!
