### ISSUE TITLE
AttributeError: '_StdoutProxy' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by ChemGuy88** [verigak/progress#52]
I did some reading online and it mentioned monkey patching. Any tips on how I can do that in this case?

Here's the complete traceback:

```
In [45]: spinner = Spinner('')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-edb2ea8bc262> in <module>()
----> 1 spinner = Spinner('')

~/.local/lib/python3.6/site-packages/progress/helpers.py in __init__(self, message, **kwargs)
     29             self.message = message
     30 
---> 31         if self.file.isatty():
     32             if self.hide_cursor:
     33                 print(HIDE_CURSOR, end='', file=self.file)
```

**Comment by verigak** [comment]
What's your environment? Are you just importing progress in ipython?

**Comment by edwardbarak** [comment]
I have same issue and yes, I am importing progress in ipython. Is it not how it's supposed to be used? It was working for me earlier.

**Comment by verigak** [comment]
Closing this as it seems to be solved with `check_tty=False`. Let me know if there are other cases.
