### ISSUE TITLE
Add custom variable to the bar

### ISSUE THREAD

**Issue by javierin** [verigak/progress#60]
Hi
I know suffixes can include text, but I would like to append a variable to the suffix, so it is updated along with the percentage. Would that be feasible?

My use case is:
I have a progress bar which outputs the progress of a video transcode. I'd like to append the frames per second value and current output file size right after the progress percentage
`Transcoding |█                               | 3% 123.45 fps Current Size: 12345MB`

I already have that variables which update regularly, but can't figure out how to make them appear in the suffix and be updated as the progress bar changes.

Is this even possible?
Thanks

**Comment by verigak** [comment]
You can do this by assigning a custom attribute to your bar and using it on the suffix. Unfortunately suffix is used on initialization, so it needs to happen afterwards. Here is an example:

```python
with Bar('Transcoding', max=20) as bar:
    bar.fps = 0
    bar.suffix = '%(percent)d%% %(fps)f fps'
    for i in range(20):
        bar.fps = update_fps()
        # ...
        bar.next()
```
