### ISSUE TITLE
Program abrupt termination (^C) should reset cursor state

### ISSUE THREAD

**Issue by clintolsen** [verigak/progress#64]
Since progress hides the cursor, if the program exits/crashes prematurely or is interrupted via the keyboard, the cursor state is left in the hidden mode. Some attempt should be made to restore this state under most circumstances.

**Comment by frasern** [comment]
Pull request #64 should resolve this.

**Comment by set-leanix** [comment]
Any progress on reviewing the related PR? I really like this library but this issue is a real deal breaker unfortunately. I also tested the PR locally. It works fine and the code looks fine too.

**Comment by set-leanix** [comment]
Thanks @verigak is there a release planned for this soon?

**Comment by verigak** [comment]
There isn't a lot of stuff since last release yet and in any case I like to leave a small period of time in case any bugs come up. Ping me up again in a couple weeks and I'll do a release then.

**Comment by set-leanix** [comment]
Why not doing a patch level release 1.5.1 then? I can gladly help out but it's a mere version bump, `python setup.py bdist_wheel` and `twine upload dist/*`. Why wait for weeks with that?

**Comment by luliangce** [comment]
according the [atexit](https://docs.python.org/3.8/library/atexit.html)‘s doc, it  cannot  reslove problem sometimes，

**Comment by teresaejunior** [comment]
My cursor is not restored even with atexit.register(bar.finish)
