### ISSUE TITLE
Does this works on Google Colab or Jupyter Notebook ?

### ISSUE THREAD

**Issue by AkiMosi** [verigak/progress#80]
Hello, Your work is so good.
I tried to use this package in both Jupyter Notebook and in Colab, but I can't see any bars!

**Comment by waylonflinn** [comment]
I also had this problem. The following worked for me.

```python
Bar.check_tty = False
bar = Bar('Progress', max=20)
```
Before creating your progress bar set `check_tty` to `False` on the class.

**Comment by AkiMosi** [comment]
Thanks a lot, tried it. It works fine.
It printed the progress bar without the red ```stderr``` box, even without using this line below
```py
Bar.file = sys.stdout
```
